<template>
  <div class="switch-distraction" :class="{'is-active': distraction}">
    <el-switch active-text="On" inactive-text="Off" v-model="distraction" title="Toggles Distraction Free Mode"/>
    <p style="font-size: x-small">Distracted? Turn on the new distraction free mode to focus on what's important!</p>
  </div>
  <el-main v-if="!distraction" style="margin-top: 6em; ">
    <el-row justify="center">
      <el-col :lg="12" :md="24">
        <h1>Welcome to your Ok!-Bot</h1>
        <h2>Overall Status Report</h2>
        <p>
          In order to not make the user unnecessarily nervous,
          the status level is always green and has a fixed value of 85%.
        </p>

        <el-progress :percentage="85" status="success"/>
        <el-text><strong>Everything Is Possibly Ok{{ formattedConfidenceLevel }}</strong></el-text>
      </el-col>
    </el-row>
    <el-row justify="center" style="margin-top: 80px">
      <el-col :lg="12" :md="24">
        <p>
          The confidence level is displayed as a slider.
          The user can adjust the confidence level.
          The confidence level is displayed as a number.
          <br>
          <small style="font-size: x-small; font-style: italic;">This text was generated by an AI.</small>
        </p>
        <el-slider :min="-2" :max="122" v-model="confidenceLevel"/>
        <el-text>Confidence Level: {{ confidenceLevel }}</el-text>
        <p v-show="message">
          <el-text>{{ message }}</el-text>
        </p>
      </el-col>
    </el-row>
    <el-row justify="center" style="margin-top: 80px">
      <el-col :lg="12" :md="24">
        <h3>Ok!-Bot offers a clean and easy UI with simple buttons not hiding their functionality</h3>
        <el-popover
            :visible="counter[0] >= 10"
            placement="bottom"
            title="Information!"
            :width="200"
            content="You reached maximum functionality. Please user other button"
        >
          <template #reference>
            <el-button @click="click(0)" :style="{transform: transform(0), zIndex: counter[0]}"
                       :disabled="counter[0] >= 10">Functionality
            </el-button>
          </template>
        </el-popover>

        <el-popover
            :visible="counter[1] >= 10"
            placement="bottom"
            title="Information!"
            :width="200"
            content="You reached maximum functionality. Please user other button"
        >
          <template #reference>
            <el-button @click="click(1)" :style="{transform: transform(1), zIndex: counter[1]}"
                       :disabled="counter[1] >= 10">Functionality
            </el-button>
          </template>
        </el-popover>

      </el-col>
    </el-row>

    <el-row justify="center" style="margin-top:2em">
      <el-col :lg="12" :md="24">
        <h2 class="new">On Demand Checks!</h2>
        <el-input placeholder="Enter A URL ..." v-model="url"></el-input>
        <el-button :disabled="url.length === 0" @click="doCheck(0)">Check</el-button>
        <p v-show="checkMessage">{{checkMessage}}</p>
        <ul>
          <li v-for="message in checkedMessages">
            {{message}}
          </li>
        </ul>
      </el-col>
    </el-row>

    <el-row justify="center" style="margin-top: 2em">
      <el-col :lg="12" :md="24">
        <h3>With Ok!-Bot, you can monitor anything that is important to you:</h3>
        <el-table table-layout="fixed" :data="data" style="width: 100%" height="250">
          <el-table-column sortable fixed prop="name" label="Monitor"  />
          <el-table-column sortable prop="status" label="Status"  />
          <el-table-column sortable prop="percentage" label="%"  />
        </el-table>

      </el-col>
    </el-row>
    <el-row justify="center" style="margin: 5em 0">
      <el-col :lg="12" :md="24">
        <h2>Coming soon</h2>
        <p>
          At Ok!-Bot we are listening to our users!
          We are constantly improving our product to make it the best it can be.
          Here are some features that are coming soon:
        </p>
        <h3>Dark Mode!</h3>
        <p>
          Ok!-Bot will soon offer a dark mode to reduce eye strain. See a Screenshot:
        </p>
        <div class="preview-dark-mode"></div>
      </el-col>
    </el-row>



  </el-main >
  <el-main class="distraction-free" v-else>
    <span class="gigantic">85%</span>
  </el-main>
</template>
<script setup lang="ts">
import {computed, onMounted, reactive, ref, watch} from 'vue'
import {watchDebounced} from "@vueuse/core";

const counter = reactive([0, 0])
const sliderCount = ref(0)
const confidenceLevel = ref(77)
const message = ref("")
const checkMessage = ref("")
const numClicks = ref(0)
const distraction = ref(false)
const url = ref("")
const checkedMessages = reactive<Array<string>>([])

const data = reactive(new Array<{ name: string, status: string, percentage: number }>())

for (let n=0; n < 100; n++) {
  data.push({
    name: "Data",
    status: "Possibly Ok",
    percentage: 85
  })
}



const formattedConfidenceLevel = computed(() => {
  if (confidenceLevel.value >= 73) {
    return "!"
  } else if (confidenceLevel.value >= 29) {
    return "."
  } else {
    return "?"
  }
})

function doCheck(n: number) {
  const checkMessages = [
    "dns",
    "ping",
    "https",
    "ssl",
    "room temperature",
    "cpu",
    "memory",
    "disk space",
    "network",
    "uptime",
    "dns (again, it's important!)",
  ]

  const timeout = Math.random() * 5000

  checkMessage.value = `Checking ${checkMessages[n]} ...`
  setTimeout(() => {
    checkedMessages.push(`${checkMessages[n]}: Possibly Ok!`)
    setTimeout(() => {
      checkMessage.value = ""
      n++
      if (n < checkMessages.length)
        doCheck(n)
    }, 2000)
  }, timeout)

}

function transform(button: number) {
  const sign = numClicks.value > 20 ? -1 : 1
  return `scale(${sign * (1 + counter[button] / 10)}, ${1 + counter[button] / 10})`
}

function click(button: number) {
  numClicks.value++
  counter[button]++
  if (button === 0) {
    counter[1] = 0
  } else {
    counter[0] = 0
  }
}

watchDebounced(
    confidenceLevel,
    () => {
      sliderCount.value++
    },
    {debounce: 500, immediate: true},
)

watch(sliderCount, () => {
      if (sliderCount.value > 10) {
        message.value = "You got that slider business under control!"
        if (counter.every(n => n === 0)) {
          message.value += " Maybe you should try the buttons now?"
        } else {
          message.value += " You should try the buttons again!"
        }
      } else if (sliderCount.value > 7) {
        message.value = "You are very good at using the slider. Keep going!"
      } else if (sliderCount.value > 3) {
        message.value = "You are getting the hang of it!"
      }
    }
)

watch(() => counter, () => {
  if (counter.some((n) => n >= 10)) {
    sliderCount.value = 0
    message.value = ""
  }
}, {deep: true})



</script>

<style lang="scss">
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap');

html, body {
  height: 100%;
}

body {
  font-family: 'Roboto', sans-serif;
  position: relative;
}

#app {
  height: 100%;
}

.el-main {
  justify-content: center;
  align-items: center;
  &.distraction-free {
    display: flex;
    height: 100%;
    justify-content: center;
    align-items: center;
    .gigantic {
      font-size: 100px
    }
  }

}

.el-button {
  transition-property: transform;
  transition-duration: 1s;
  position: relative;
}

.switch-distraction {
  position: fixed;
  top: 0;
  right: 0;
  display: flex;
  flex-direction: column;
  justify-content: right;
  width: 10em;

  p {
    margin-right: 2em;
  }
  &.is-active {
    opacity: 0.2 !important;
  }

}


.flashlight {
  position: absolute;
  top: 100px;
  left: 100px;
  width: 100px;
  height: 100px;
  backdrop-filter: opacity(0.2);
  background-color: rgb(255 255 255 / 0.3);
}

.new {
  background-image: url("")
}

.preview-dark-mode {
  width: 100%;
  height: 20vh;
  background-color: #333333;
}


</style>
